# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e356095bb9c54886b784a8003f6044af69bd52e77cd0c89f85451af3d78262df004a70befa9847fb28878088c09737d7dfd0adfd4d187994566a1a8452b70dd

test:
  secret_key_base: 1f0b8bf773a3a7202c3ba81ba7f55740cd071fe0b11b02c923850ffb3aed3bb8343b7255e973d716ef6c1b8d912bee6e1e678d38e808575a2a62de2c04baec8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
